language: python


python:
    - "2.7"


install:
    - pip install -r ProyectoAPI/Autenticacion1718G2/requirements.txt
    - pip install coverage

sudo: required

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_8db431787d56_key -iv $encrypted_8db431787d56_iv -in deploy.enc -out deploy -d
  # INICIO DE DESPLIEGUE EN UN CONTENEDOR DE LA BASE DE DATOS DEL SISTEMA DE 
  #    VOTACIONES
  - mkdir mysql_build
  - cd mysql_build
  - curl -O https://raw.githubusercontent.com/EGC-G2-Trabajo-1718/integracion/master/docker/dockerfiles/mysql/init.sql
  - curl -O https://raw.githubusercontent.com/EGC-G2-Trabajo-1718/integracion/master/docker/dockerfiles/mysql/Dockerfile
  - docker build -t egc/mysql .
  - docker network create --subnet=172.18.0.0/16 dev
  - docker run -d --network=dev --ip=172.18.2.2 -e MYSQL_ROOT_PASSWORD=nothing egc/mysql
  - cd ..
  # FIN DEL DESPLIEGUE, YA SE PUEDEN REALIZAR TESTS CON LA BD

before_deploy:
  - chmod 600 deploy && mv deploy ~/.ssh/id_rsa
  - curl -O https://raw.githubusercontent.com/EGC-G2-Trabajo-1718/integracion/master/tools/deploy.sh
  # ADMINISTRACIÓN DE VOTACIONES: DESCOMENTAR SIGUIENTE LÍNEA
  # - scp target/*.war deploy@egc.duckdns.org:g2/tmp/ROOT.war

deploy:
  skip_cleanup: true
  provider: script
  script: ssh deploy@egc.duckdns.org 'bash -s' < deploy.sh autenticacion # INSERTAR NOMBRE DEL SUBSISTEMA ESPECIFICADO EN LA WIKI SIN LOS CARACTERES "< >"
  on:
    branch: master

after_success: coverage report

script:
    - python ProyectoAPI/Autenticacion1718G2/manage.py test